const { getDb } = require('../config/firebase')
const { buildContext } = require('../brain/context/context-builder')
const { executeReflection } = require('../brain/modules/reflection-engine')
const { updateMemory } = require('../brain/modules/memory-engine')
const { createFallbackPlanningOutput } = require('../brain/schemas/planning.schema')

/**
 * Reflection Service.
 * Manages daily reflection logging and updates the AI memory insights.
 *
 * References: TDD §31, AISPEC §13
 */

/**
 * Validates daily reflection input.
 *
 * @param {Object} data
 * @returns {string[]|null}
 */
function validateReflectionInput(data) {
  const errors = []
  if (!data) return ['Payload is null or undefined.']

  const rating = Number(data.productivityRating)
  if (isNaN(rating) || rating < 1 || rating > 5) {
    errors.push('productivityRating must be a number between 1 and 5.')
  }

  if (data.notes && typeof data.notes !== 'string') {
    errors.push('notes must be a string.')
  }

  if (data.blockers && !Array.isArray(data.blockers)) {
    errors.push('blockers must be an array of strings.')
  }

  if (data.completedTasks && !Array.isArray(data.completedTasks)) {
    errors.push('completedTasks must be an array of strings.')
  }

  return errors.length > 0 ? errors : null
}

/**
 * Records a user's daily reflection and updates memory observations.
 *
 * @param {string} userId
 * @param {Object} reflectionData
 * @returns {Promise<Object>} The insights and recommendations generated by the run
 */
async function recordDailyReflection(userId, reflectionData) {
  const errors = validateReflectionInput(reflectionData)
  if (errors) {
    throw new Error(`VALIDATION_ERROR: ${errors.join(', ')}`)
  }

  const db = getDb()
  if (!db) {
    throw new Error('Database connection is unavailable.')
  }

  const now = new Date().toISOString()

  // 1. Log reflection to Firestore reflections collection
  const reflectionDoc = {
    userId,
    productivityRating: Number(reflectionData.productivityRating),
    completedTasks: reflectionData.completedTasks || [],
    blockers: reflectionData.blockers || [],
    notes: reflectionData.notes || '',
    createdAt: now,
  }

  await db.collection('reflections').add(reflectionDoc)
  console.log(`[Reflection Service] Recorded daily reflection doc for user: ${userId}`)

  // 2. Re-build user context to include the newly logged reflection
  const context = await buildContext(userId)

  // 3. Formulate empty inputs for reasoning/decisions/plans to trigger reflection analyzer
  const lastSchedule = context.previousSchedules?.[0] || {}
  const dummyReasoning = { extractedTasks: [], detectedRisks: [], estimatedWorkload: 0, summary: '', confidence: 100 }
  const dummyDecisions = { priorityOrdering: [], urgencyAssessment: {}, focusRecommendations: [], deferredTasks: [], blockedTasks: [], confidence: 100 }
  const dummyPlanning = {
    planningResult: { status: 'success', message: '' },
    taskPriorities: [],
    schedule: lastSchedule.taskBlocks ? [lastSchedule] : [],
    recommendations: [],
    summary: '',
    confidence: 100,
  }

  // 4. Run Reflection Engine analysis via Gemini
  console.log('[Reflection Service] Initiating Reflection Engine analysis...')
  const reflectionOutput = await executeReflection(context, dummyReasoning, dummyDecisions, dummyPlanning)

  // 5. Update Memory insights profile with the new observations
  console.log('[Reflection Service] Triggering Memory insights update...')
  const dummyCoaching = { coachingMessages: [], dailySummary: '', confidence: 100 }
  await updateMemory(context, dummyPlanning, reflectionOutput, dummyCoaching)

  return {
    reflectionSummary: reflectionOutput.reflectionSummary,
    insights: reflectionOutput.insights,
    recommendations: reflectionOutput.recommendations,
    confidence: reflectionOutput.confidence,
  }
}

module.exports = { recordDailyReflection }
